name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose -f ./docker-compose.yml up -d --build
    - name: Migrate
      run: docker-compose -f ./docker-compose.yml exec web python manage.py migrate --noinput
    - name: Statics
      run: docker-compose -f ./docker-compose.yml exec web python manage.py collectstatic --noinput
