name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: docker-compose -f ./docker-compose.yml up -d --build
    - name: Migrate
      run: docker-compose -f ./docker-compose.yml exec -T web python manage.py migrate
    - name: Statics
      run: docker-compose -f ./docker-compose.yml exec -T web python manage.py collectstatic
    - name: Tests
      run: docker-compose -f ./docker-compose.yml exec -T web python manage.py test
