name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker-compose -f docker-compose.yml up -d --build && docker-compose -f docker-compose.yml exec web python manage.py migrate --noinput && docker-compose -f docker-compose.yml exec web python manage.py collectstatic --noinput 
